# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 17:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("people", "0004_auto_20151221_1110")]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Active", models.BooleanField(default=True)),
                ("Last_Updated", models.DateTimeField(auto_now=True)),
                (
                    "Name",
                    models.CharField(
                        help_text=b"A descriptive name.", max_length=64, unique=True
                    ),
                ),
                (
                    "Short_Name",
                    models.SlugField(
                        help_text=b"A short name suitable for use in a url.",
                        unique=True,
                    ),
                ),
                (
                    "Chair",
                    models.ForeignKey(
                        help_text=b'Only people with the "committee" flag are shown',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_chair",
                        to="people.Person",
                    ),
                ),
                (
                    "Members",
                    models.ManyToManyField(
                        help_text=b'Only people with the "committee" flag are shown',
                        related_name="committee_members",
                        to="people.Person",
                    ),
                ),
            ],
            options={"ordering": ["Name"]},
        )
    ]
