# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("committee", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="Chair",
            field=models.ForeignKey(
                help_text=b'Only people with the "committee" flag are shown',
                on_delete=django.db.models.deletion.PROTECT,
                related_name="committee_chair",
                to="people.Person",
            ),
        )
    ]
