# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 14:51
from __future__ import unicode_literals

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("committee", "0003_auto_20170929_0942")]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="chair",
            field=models.ForeignKey(
                help_text='Only people with the "committee" flag are shown',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committee_chair",
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text='Only people with the "committee" flag are shown',
                related_name="committee_members",
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="name",
            field=models.CharField(
                help_text="A descriptive name.", max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                help_text="A short name suitable for use in a url.",
                populate_from="name",
                unique=True,
            ),
        ),
    ]
