# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("committee", "0004_auto_20170929_0951")]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="means_of_selection",
            field=models.TextField(
                blank=True, help_text="This will be processed as ReStructuredText"
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="membership",
            field=models.TextField(
                blank=True, help_text="This will be processed as ReStructuredText"
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="quorum",
            field=models.CharField(
                blank=True,
                help_text="the minimum number of members to make meetings valid",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="remarks",
            field=models.TextField(
                blank=True, help_text="This will be processed as ReStructuredText"
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="term",
            field=models.CharField(
                blank=True,
                help_text="The length of time individual member of the committee normally serves",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="terms_of_reference",
            field=models.TextField(
                blank=True, help_text="This will be processed as ReStructuredText"
            ),
        ),
    ]
