# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("committee", "0007_auto_20170929_1149"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("chair", models.BooleanField(default=False)),
                ("ex_officio", models.BooleanField(default=False)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committee.Committee",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text='Only people with the "committee" flag are shown',
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
            ],
            options={"ordering": ["-chair", "person"]},
        )
    ]
